-- SQL Migration to add 'status' column to the 'bookings' table
-- Run this script in the Supabase SQL Editor (Dashboard -> SQL Editor -> New Query)

-- 1. Add status column if it does not already exist
ALTER TABLE bookings 
ADD COLUMN IF NOT EXISTS status VARCHAR(50) DEFAULT 'pending';

-- 2. Backfill existing null records to 'pending'
UPDATE bookings 
SET status = 'pending' 
WHERE status IS NULL;


-- 3. Create portfolio table
CREATE TABLE IF NOT EXISTS portfolio (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  url TEXT NOT NULL,
  thumbnail_url TEXT,
  tier_tag TEXT,
  display_order INT DEFAULT 0 NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE portfolio ENABLE ROW LEVEL SECURITY;

-- 5. Create policy to allow read access for everyone
CREATE POLICY "Allow public read access" ON portfolio
  FOR SELECT USING (true);

