-- GNG Corporation - Supabase Database Schema & Seeding Script
-- Copy and run this script in your Supabase SQL Editor.

-- =========================================================================
-- 1. SERVICES TABLE SCHEMA
-- =========================================================================
CREATE TABLE IF NOT EXISTS services (
  id bigint generated by default as identity primary key,
  category text not null, -- 'ai-agent' or 'web-package'
  name text not null,
  description text not null,
  price text not null, -- e.g. "499" or "1,499"
  price_period text not null, -- e.g. "/ month" or "one-time"
  features jsonb not null default '[]'::jsonb, -- array of strings, e.g. ["Feature 1", "Feature 2"]
  active boolean not null default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- =========================================================================
-- 2. ROW LEVEL SECURITY (RLS) POLICIES
-- =========================================================================

-- Enable RLS on services table
ALTER TABLE services ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public/anonymous reads of active services
DROP POLICY IF EXISTS "Allow public read-only of active services" ON services;
CREATE POLICY "Allow public read-only of active services"
ON services FOR SELECT
TO anon, authenticated
USING (active = true);

-- Policy: Allow full CRUD operations for authenticated admins
DROP POLICY IF EXISTS "Allow admin full access to services" ON services;
CREATE POLICY "Allow admin full access to services"
ON services FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Enable RLS on bookings (leads) table
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public/anonymous users to insert lead entries (guest form submission)
DROP POLICY IF EXISTS "Allow public insert to bookings" ON bookings;
CREATE POLICY "Allow public insert to bookings"
ON bookings FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- Policy: Allow full access (select, delete, update) to lead records for authenticated admins
DROP POLICY IF EXISTS "Allow admin full access to bookings" ON bookings;
CREATE POLICY "Allow admin full access to bookings"
ON bookings FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- =========================================================================
-- 3. SEED INITIAL SERVICES DATA
-- =========================================================================
-- Clear existing seeded services to avoid duplication
TRUNCATE TABLE services RESTART IDENTITY CASCADE;

INSERT INTO services (category, name, description, price, price_period, features, active) VALUES
-- AI AGENTS
(
  'ai-agent', 
  'WhatsApp AI Agent', 
  'Automates customer conversations, answers catalog details, and books client appointments instantly through the WhatsApp Business API.', 
  '499', 
  '/ month', 
  '["WhatsApp Business API Integration", "24/7 Instant Automated Replies", "Appointment & Booking Flow", "Catalog Information Lookup", "Lead Data Export"]'::jsonb, 
  true
),
(
  'ai-agent', 
  'Gmail AI Agent', 
  'Monitors your primary inboxes, draft-replies contextually, escalates complex inquiries, and runs persistent CRM follow-ups.', 
  '399', 
  '/ month', 
  '["Contextual Email Draft Replies", "Inbox Monitoring & Triage", "CRM Automatic Syncing", "Smart Escalation Alerts", "Operational Telemetry"]'::jsonb, 
  true
),
(
  'ai-agent', 
  'YouTube Agent', 
  'Automates metadata generation, handles active comment filtering, responds to viewers, and drafts SEO descriptions based on uploaded footage.', 
  '599', 
  '/ month', 
  '["SEO Description Drafts", "Comment Sentiment Filtering", "Automated Viewer Replies", "Instant Metadata Tuning", "Platform Performance Metrics"]'::jsonb, 
  true
),
(
  'ai-agent', 
  'Google Sheets Agent', 
  'Syncs real-time operations telemetry, analyzes workflow anomalies, runs programmatic mathematical models, and generates weekly reporting.', 
  '349', 
  '/ month', 
  '["Real-time Telemetry Syncing", "Anomaly Alerts & Flags", "Weekly Automated Reports", "Programmatic Math Models", "Data Export Workflows"]'::jsonb, 
  true
),
(
  'ai-agent', 
  'General AI Chatbot', 
  'Fully customized, vector-embedded RAG bots tailored to index your company''s knowledge base, documents, and wikis securely.', 
  '599', 
  '/ month', 
  '["Vector-Embedded RAG", "Secure Knowledge Base Syncing", "Multi-file Context Indexing", "Enterprise Guardrails", "Analytics Telemetry Panel"]'::jsonb, 
  true
),

-- STANDARD WEB PACKAGES
(
  'web-package', 
  'Standard Starter', 
  'A clean, fast, and modern informational website tailored to showcase your services and brand with elite aesthetics.', 
  '1,499', 
  'one-time', 
  '["Premium Minimal Design", "Fully Responsive Layout", "Speed Optimization (90+ mobile)", "Basic Contact Form Node", "3 Revision Rounds"]'::jsonb, 
  true
),
(
  'web-package', 
  'Standard + Database', 
  'Integrates a robust SQL database node. Perfect for user registrations, lead storage list capture, and dynamic data presentation.', 
  '2,499', 
  'one-time', 
  '["Everything in Starter", "PostgreSQL Database Node", "Dynamic Lead Storage Flow", "Admin Leads Viewer Pane", "5 Revision Rounds"]'::jsonb, 
  true
),
(
  'web-package', 
  'Standard + DB + Admin', 
  'A complete operational platform featuring custom client accounts, CRUD operations, database controls, and system state metrics.', 
  '3,999', 
  'one-time', 
  '["Everything in DB Tier", "Client Account Portals", "Custom CRUD Dashboard Panel", "Advanced Database Security", "Unlimited Revisions"]'::jsonb, 
  true
),

-- IMMERSIVE WEB PACKAGES
(
  'web-package', 
  '3D Starter', 
  'Step into the next generation. We integrate interactive Spline canvases and high-fidelity 3D assets into a smooth user interface.', 
  '4,499', 
  'one-time', 
  '["Spline Interactive Canvas", "Custom 3D Asset Loading", "Fluid Framer-Motion Physics", "High-Fidelity UI Styling", "5 Revision Rounds"]'::jsonb, 
  true
),
(
  'web-package', 
  '3D + Database', 
  'Combines WebGL rendering engine structures with PostgreSQL storage. Build interactive stores, 3D configurators, and user dashboards.', 
  '5,999', 
  'one-time', 
  '["Everything in 3D Starter", "PostgreSQL State Syncing", "Interactive 3D Stores", "Customer Portal Dashboards", "10 Revision Rounds"]'::jsonb, 
  true
),
(
  'web-package', 
  '3D + DB + Admin', 
  'Our signature build. Complete WebGL interactivity, multi-node database architectures, and telemetry-focused analytics admin dashboards.', 
  '8,999', 
  'one-time', 
  '["Everything in 3D + DB", "Custom WebGL Scenes", "Comprehensive Analytics Panel", "Advanced Telemetry Widgets", "Lifetime Code Support"]'::jsonb, 
  true
);
